// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using hotchocolate_playground;

namespace hotchocolate_playground.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210731172223_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.8");

            modelBuilder.Entity("hotchocolate_playground.Example", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id", "TypeId");

                    b.ToTable("Examples");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TypeId = 1
                        },
                        new
                        {
                            Id = 1,
                            TypeId = 2
                        },
                        new
                        {
                            Id = 1,
                            TypeId = 3
                        },
                        new
                        {
                            Id = 1,
                            TypeId = 4
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
