// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using hotchocolate_playground;

namespace hotchocolate_playground.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.8");

            modelBuilder.Entity("hotchocolate_playground.Example", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id", "TypeId");

                    b.ToTable("Examples");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TypeId = 1
                        },
                        new
                        {
                            Id = 1,
                            TypeId = 2
                        },
                        new
                        {
                            Id = 1,
                            TypeId = 3
                        },
                        new
                        {
                            Id = 2,
                            TypeId = 4
                        });
                });

            modelBuilder.Entity("hotchocolate_playground.WrapperClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExampleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExampleId", "TypeId");

                    b.ToTable("WrapperClasses");

                    b.HasData(
                        new
                        {
                            Id = 5,
                            ExampleId = 2,
                            TypeId = 4
                        });
                });

            modelBuilder.Entity("hotchocolate_playground.WrapperClass", b =>
                {
                    b.HasOne("hotchocolate_playground.Example", "Example")
                        .WithMany("WraperClasses")
                        .HasForeignKey("ExampleId", "TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Example");
                });

            modelBuilder.Entity("hotchocolate_playground.Example", b =>
                {
                    b.Navigation("WraperClasses");
                });
#pragma warning restore 612, 618
        }
    }
}
